config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    authenticated :user do
      root 'users#index', as: :authenticated_root
    end

    unauthenticated :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :inventories , only: %i[index new create]

  resources :votes , only: %i[create new]

  resources :trades , only: %i[show create destroy new] do
    member do
      post 'accept_request'
    end
  end

  resources :users , only: %i[show edit index update]do
    collection do
      get 'report'
      get 'requests'
    end
  end
  get '/*path', to: 'users#index'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :vote_sent_comparison, foreign_key: :vote_sent_id, class_name: 'Vote', dependent: :destroy
  has_many :vote_reciever, through: :vote_sent_comparison

  has_many :vote_reciever_comparison, foreign_key: :vote_reciever_id, class_name: 'Vote', dependent: :nullify
  has_many :vote_sent, through: :vote_reciever_comparison

  has_many :sending_user_comparison, foreign_key: :sending_user_id, class_name: 'Trade', dependent: :nullify
  has_many :recieving_user, through: :sending_user_comparison

  has_many :recieving_user_comparison, foreign_key: :recieving_user_id, class_name: 'Trade', dependent: :nullify
  has_many :sending_user, through: :recieving_user_comparison

  has_one :inventory, dependent: :destroy

  validates :name, format: { with: /\A[a-zA-Z]+\z/, message: 'Should contain letters Only' }, presence: true

  validates :age, inclusion: { in: 18..90 }, presence: true

  validates :longitude, inclusion: { in: -180..180 }, presence: true

  validates :latitude, inclusion: { in: -90..90 }, presence: true

  enum status: {
    Not_Infected: 0,
    Infected: 1
  }

  enum user_type: {
    user: 0,
    admin: 1
  }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

module Users
  class ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # You should configure your model like this:
    # devise :omniauthable, omniauth_providers: [:twitter]

    # You should also create an action method in this controller like this:
    # def twitter
    # end

    # More info at:
    # https://github.com/heartcombo/devise#omniauth

    # GET|POST /resource/auth/twitter
    # def passthru
    #   super
    # end

    # GET|POST /users/auth/twitter/callback
    # def failure
    #   super
    # end

    # protected

    # The path used when OmniAuth fails
    # def after_omniauth_failure_path_for(scope)
    #   super(scope)
    # end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params
    # , only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up

    # POST /resource

    # GET /resource/edit

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update]
  before_action :authorize_action, only: %i[show edit update]

  def show
    @user.Infected! if Vote.votes_count(@user) >= 5
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Updated Sucessfully'
    else
      render 'edit', notice: 'can not be Updated'
    end
  end


  def index
    if current_user.admin?
      redirect_to report_users_path, notice: 'Admin Pannel'
    elsif current_user.user? && current_user.inventory.nil?
      redirect_to new_inventory_path, notice: 'Register Your Inventory'
    else
      @r = User.ransack(params[:q])
      @users = @r.result.where(user_type: :user)
    end
  end

  def report
    @users = User.where(user_type: :user)
    authorize @users
  end

  private

  def user_params
    params.require(:user).permit(:longitude, :latitude, :image)
  end

  def authorize_action
    authorize @user
  end

  def set_user
    begin
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to users_path, alert: 'Record Not Found'
    rescue Exception
      flash[:alert]= "Something is Missing"
    end

  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def vote_count(user)
    Vote.where(vote_reciever_id: user.id).count
  end

  def pending?
    Trade.find_by!(recieving_user_id: current_user.id).request_status == 'pending'
  end

  def not_effected?(user)
    ((current_user != user) && user.status == Not_Infected)
  end

  def not_voted?(user)
    !(current_user.vote_reciever.ids.include? user.id)
  end

  def not_infected_count
    User.where(status: :Not_Infected, user_type: :user).count
  end

  def infected_count
    User.where(status: :Infected).count
  end

  def total_users
    User.where(user_type: :user).count
  end

  def water_sum
    (Inventory.pluck(:water).inject(0) { |sum, i| sum + i }) / WATER_POINTS
  end

  def soup_sum
    (Inventory.pluck(:soup).inject(0) { |sum, i| sum + i }) / SOUP_POINTS
  end

  def pouch_sum
    (Inventory.pluck(:pouch).inject(0) { |sum, i| sum + i }) / POUCH_POINTS
  end

  def ak47_sum
    (Inventory.pluck(:Ak47).inject(0) { |sum, i| sum + i }) / AK47_POINTS
  end

  def average_water
    water_sum / total_users
  end

  def average_soup
    soup_sum / total_users
  end

  def average_pouch
    pouch_sum / total_users
  end

  def average_Ak47
    ak47_sum / total_users
  end
end

app/views/users/_inventoryTable.html.erb
<table class="table">
  <tr class="table-secondary">
    <th >Qty</th>
    <th>Item Name </th>
    <th>Points</th>
  </tr>
  <tr>
    <td><%=user.inventory.water / WATER_POINTS%></td>
    <td> Fiji Water</td>
    <td><%=user.inventory.water %></td>
  </tr>
  <tr>
    <td><%=user.inventory.soup / SOUP_POINTS%> </td>
    <td> Soup </td>
    <td><%=user.inventory.soup %></td>
  </tr>
  <tr>
    <td><%=user.inventory.pouch / POUCH_POINTS%> </td>
    <td> Pouch </td>
    <td><%=user.inventory.pouch %></td>
  </tr>
  <tr>
    <td><%=user.inventory.Ak47 / AK47_POINTS%> </td>
    <td> AK47 </td>
    <td><%=user.inventory.Ak47 %></td>
  </tr>
</table>

app/views/users/_row.html.erb
<td><%= user.name %></td>
<td><%= user.age%></td>
<td>
  <div style="width:50px;height:auto">
    <%= cl_image_tag(user.image.key ,style:'width:100%') if user.image.attached?%>
  </div>
</td>
<%if current_user.user?%>
<td><%= user.inventory.total_qty %></td>
<% end %>
<td><%= link_to "Detail", user_path(user), class:"btn btn-outline-success" %></td>

app/views/users/_search_form.html.erb
<%= search_form_for @r, url: :users do |f| %>
  <%= f.search_field :name_or_inventory_total_qty_cont %>
  <%= f.submit "Search" %>
  <br>
  <br>
<% end %>

app/views/users/edit.html.erb
<div class="container cont_b">
  <%if current_user.Not_Infected?%>
    <h1>Update </h1>
    <%= form_with(model: @user, local: true) do |form| %>
      <p>
        <%= form.label :longitude %><br>
        <%= form.number_field :longitude , step: 1 , min:-90, max: 90%>
      </p>
      <p>
        <%= form.label :latitude %><br>
        <%= form.number_field :latitude , step: 1 , min:-90, max: 90%>
      </p>
      <p>
        <%= form.label :image %><br>
        <%= form.file_field :image, direct_upload: true , accept:"image/png, image/gif, image/jpeg"%>
      </p>
      <p>
        <%= form.submit %>
      </p>
    <% end %>
  <% else %>
    <h1 class= "text-danger">Sorry You can not update</h1>
  <% end %>
  <%= link_to 'Back', user_path ,class:"btn btn-dark" %>
  <br>
  <br>

app/views/users/home.html.erb
<h1>Registered Users</h1>
<%= render 'search_form'%>
<table class='table table-bordered '>
  <tr class="table-danger">

    <th>Name</th>
    <th>Age</th>
    <th>Image</th>
    <th>Total Qty</th>
    <th>Details</th>

  </tr>
  <% @users.each do |user| %>
  <% if current_user!=user %>
   <tr>
        <%= render 'row', :user => user%>
    </tr>

  <% else %>
  <tr class= 'table-success'>
      <%= render 'row', :user => user%>
    </tr>


  <% end %>
<% end %>
</table>

app/views/users/index.html.erb
<h1>Registered Users</h1>
<%= render 'search_form'%>
<table class='table table-bordered '>
  <tr class="table-danger">

    <th>Name</th>
    <th>Age</th>
    <th>Image</th>
    <th>Total Qty</th>
    <th>Details</th>

  </tr>
  <% @users.each do |user| %>
  <% if current_user!=user %>
   <tr>
        <%= render 'row', :user => user%>
    </tr>

  <% else %>
  <tr class= 'table-success'>
      <%= render 'row', :user => user%>
    </tr>


  <% end %>
<% end %>
</table>

app/views/users/report.html.erb
<h1 class= 'text-center'>Report</h1>
<br>
<b>
  <table class="table">
    <tr class="table-secondary">
      <th>Infected pecentage</th>
      <th >Non Infected Percentage</th>
      <th>Average Water</th>
      <th>Average Soup</th>
      <th>Average Pouch</th>
      <th>Average AK47</th>
    </tr>
    <tr>
      <td> <%=((infected_count/total_users.to_f)*100).to_i%>% </td>
      <td><%= ((not_infected_count/total_users.to_f)*100).to_i%>% </td>
      <td> <%=average_water%></td>
      <td> <%=average_soup%></td>
      <td> <%=average_pouch%></td>
      <td> <%=average_Ak47%></td>

    </tr>
  </table>
</table>

app/views/users/requests.html.erb
<div class= "jumbotron shadow">
  <h1 class= 'text-center'>Trade Requests</h1>
  <br>
  <h1><%= current_user.name %>'s Profile</h1>
  <br>
  <table class="table">
    <tr class="table-secondary">
      <th >Person Name</th>
      <th>Accept </th>
      <th>Reject</th>
    </tr>
    <% current_user.sending_user.each do |user|%>
      <%user.sending_user_comparison.each do |trade|%>

          <% if trade.pending? %>
          <tr>
            <td><%= user.name %></td>
            <td><%= link_to 'accept', accept_request_trade_path(user.id),method: :post, class:'btn btn-success' %></td>
            <td> <%= link_to 'reject',trade_path(user.id),method: :delete,class:'btn btn-danger' %></td>
          </tr>
        <% end %>
      <% end %>
    <%end%>
  </table>
  <br>
  <div>
    <br />
    <%= link_to 'Back',user_path(current_user),class:"btn btn-secondary shadow" %>
 <div class="d-grid gap-2 col-2 mx-auto">
          <%= link_to 'Trade History',trade_path(current_user),class:"btn btn-dark" %>
        </div>
        <br>
        <br>

app/views/users/show.html.erb
<div class = 'bg-img '>
  <div class='cont_b container w-50'>
    <p>
      <h1><%=@user.name%></h1>
      <br>
      <div class='msm-img'>
        <%= cl_image_tag(@user.image.key, class: 'w', :cloud_name => Rails.application.credentials[Rails.env.to_sym][:cloud_name]) if @user.image.attached?%>
      </div>
      <br>
    </p>
    <p>
      <h3>Location: </h3>
      Lon: &nbsp;<%= @user.longitude%>,&nbsp;Lat:&nbsp;<%= @user.latitude%>
      <%if @user==current_user%>&nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to 'Update', edit_user_path(@user), class:'btn btn-secondary'%>
        <%= link_to "All Requests",requests_users_path, class:"btn btn-danger" %>
      <% end %>
    </p>
    <%=render 'inventoryTable', :user => @user%>
    <br>
    <span>Total Votes: <%= vote_count(@user)%> </span>
    <br>
    Status: <span class= "text-<%= @user.Infected? ? 'danger' : 'success' %>" ><%= @user.status %> </span>
    <%if current_user.Not_Infected? && current_user!= @user && @user.Not_Infected?%>
      <div class="d-grid gap-2 col-6 mx-auto">
        <%= link_to "Trade", new_trade_path(:user => @user.id), method: :get,class:"btn btn-dark" %>
      </div>
      <%if not_voted?(@user) %>
        <br>
        <div class="d-grid gap-2 col-6 mx-auto">
          <%= link_to "Vote", votes_path(:user => @user.id) , method: :post, class:"btn btn-danger" %>
        </div>
      <%end%>
    <% end %>
    <br>
    <%= link_to "people", users_path ,class:"btn btn-secondary btn-lg" %>
    <br>
    <br>
  </div>
</div>